AWSTemplateFormatVersion: '2010-09-09'
Description: Simple S3 bucket with CloudFront distribution

Parameters:
  BucketName:
    Type: String
    Description: Name of the S3 bucket
    Default: my-simple-s3-bucket
    ConstraintDescription: Must be a unique S3 bucket name
  GlacierTransitionDays:
    Type: Number
    Description: Days before transitioning objects to Glacier
    Default: 30
    MinValue: 1

Resources:
  # S3 Bucket
  MyS3Bucket:
    Type: AWS::S3::Bucket
    Properties:
      BucketName: !Ref BucketName
      AccessControl: Private
      LifecycleConfiguration:
        Rules:
          - Id: MoveToGlacier
            Status: Enabled
            Transitions:
              - TransitionInDays: !Ref GlacierTransitionDays
                StorageClass: GLACIER

  # S3 Bucket Policy for CloudFront
  S3BucketPolicy:
    Type: AWS::S3::BucketPolicy
    Properties:
      Bucket: !Ref MyS3Bucket
      PolicyDocument:
        Version: '2012-10-17'
        Statement:
          - Effect: Allow
            Principal:
              Service: cloudfront.amazonaws.com
            Action: s3:GetObject
            Resource: !Sub "arn:aws:s3:::${MyS3Bucket}/*"

  # CloudFront Distribution
  CloudFrontDistribution:
    Type: AWS::CloudFront::Distribution
    Properties:
      DistributionConfig:
        Enabled: true
        Origins:
          - Id: S3Origin
            DomainName: !GetAtt MyS3Bucket.DomainName
            S3OriginConfig: {}
        DefaultCacheBehavior:
          TargetOriginId: S3Origin
          ViewerProtocolPolicy: redirect-to-https
          AllowedMethods: [GET, HEAD]
          ForwardedValues:
            QueryString: false
            Cookies:
              Forward: none
        DefaultRootObject: index.html

Outputs:
  BucketName:
    Value: !Ref MyS3Bucket
  CloudFrontDomain:
    Value: !GetAtt CloudFrontDistribution.DomainName